// Mocks generated by Mockito 5.4.6 from annotations
// in pm25_app/test/aqi_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pm25_app/core/loggers/log.dart' as _i2;
import 'package:pm25_app/core/services/data_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppLogger_0 extends _i1.SmartFake implements _i2.AppLogger {
  _FakeAppLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i3.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppLogger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeAppLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.AppLogger);

  @override
  _i4.Future<List<dynamic>> fetchSiteData(String? site) => (super.noSuchMethod(
        Invocation.method(
          #fetchSiteData,
          [site],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
}
