// Mocks generated by Mockito 5.4.6 from annotations
// in pm25_app/test/aqi_data_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pm25_app/features/aqi/aqi_provider.dart' as _i2;
import 'package:pm25_app/features/aqi/aqi_record%EF%BC%BFmodel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AqiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAqiProvider extends _i1.Mock implements _i2.AqiProvider {
  MockAqiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AqiRecord> get records => (super.noSuchMethod(
        Invocation.getter(#records),
        returnValue: <_i3.AqiRecord>[],
      ) as List<_i3.AqiRecord>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.AqiRecord> get recentThreeHoursRecords => (super.noSuchMethod(
        Invocation.getter(#recentThreeHoursRecords),
        returnValue: <_i3.AqiRecord>[],
      ) as List<_i3.AqiRecord>);

  @override
  int get recentThreeHoursCount => (super.noSuchMethod(
        Invocation.getter(#recentThreeHoursCount),
        returnValue: 0,
      ) as int);

  @override
  double get recentThreeHoursAveragePm25 => (super.noSuchMethod(
        Invocation.getter(#recentThreeHoursAveragePm25),
        returnValue: 0.0,
      ) as double);

  @override
  String get recentThreeHoursTimeRange => (super.noSuchMethod(
        Invocation.getter(#recentThreeHoursTimeRange),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#recentThreeHoursTimeRange),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadAqi(String? site) => (super.noSuchMethod(
        Invocation.method(
          #loadAqi,
          [site],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
