// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBWYGZEIUzqop4lnl2jJAZrQFBs7ABQI',
    appId: '1:991354765232:web:a8a65d2653500d3dd8e075',
    messagingSenderId: '991354765232',
    projectId: 'pm25-app-ccfff',
    authDomain: 'pm25-app-ccfff.firebaseapp.com',
    storageBucket: 'pm25-app-ccfff.firebasestorage.app',
    measurementId: 'G-F7TWVS71H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHp1TuSAYJO4SYTCsBuYaG-HqdqcenXgM',
    appId: '1:991354765232:android:259238cd8c8136acd8e075',
    messagingSenderId: '991354765232',
    projectId: 'pm25-app-ccfff',
    storageBucket: 'pm25-app-ccfff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZg74cEdPcnXshBBmgKnMxtuyzXDiJZAg',
    appId: '1:991354765232:ios:b6f91c5573af9ea5d8e075',
    messagingSenderId: '991354765232',
    projectId: 'pm25-app-ccfff',
    storageBucket: 'pm25-app-ccfff.firebasestorage.app',
    iosBundleId: 'com.example.pm25App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZg74cEdPcnXshBBmgKnMxtuyzXDiJZAg',
    appId: '1:991354765232:ios:b6f91c5573af9ea5d8e075',
    messagingSenderId: '991354765232',
    projectId: 'pm25-app-ccfff',
    storageBucket: 'pm25-app-ccfff.firebasestorage.app',
    iosBundleId: 'com.example.pm25App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJBWYGZEIUzqop4lnl2jJAZrQFBs7ABQI',
    appId: '1:991354765232:web:be34e9adebf3bb0ed8e075',
    messagingSenderId: '991354765232',
    projectId: 'pm25-app-ccfff',
    authDomain: 'pm25-app-ccfff.firebaseapp.com',
    storageBucket: 'pm25-app-ccfff.firebasestorage.app',
    measurementId: 'G-SN0MDCGZNL',
  );
}
